[package]
name = "tiny"
version = "0.1.0"
edition = "2024"

[dependencies]
luaenv = { path = "../luaenv" }
agent-base = { path = "../agent-base" }
provider-openai = { path = "../provider-openai" }

bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["json", "stream"] }
futures-util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

async-trait = { workspace = true }
