[package]
name = "llm-openai"
version = "0.1.0"
edition = "2024"

[dependencies]
llm = { path = "../llm" }

bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["json", "stream"] }
futures-util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
